export let products = [
  {
    id: "1",
    img: "/images/tertis.jpg",
    title: "Lego set With customized models",
    stars: 5,
    price: "6999",
    oldPrice: "9000",
    location: "Lego Store, kharadi",
    isSale: true,
  },
  {
    id: "2",
    img: "/images/bear.jpg",
    title: "soft Toy brown teddy",
    stars: 4,
    price: "899",
    oldPrice: "599",
    location: "Teddy Shop, kharadi",
    isSale: true,
  },
  {
    id: "3",
    img: "/images/shirt.jpg",
    title: "H&M cotton tshirt",
    stars: 4,
    price: "1200",
    oldPrice: "1999",
    location: "H&M, kharadi",
    isSale: true,
  },
  {
    id: "4",
    img: "/images/baby.jpg",
    title: "Barbie SET",
    stars: 3,
    price: "6999",
    oldPrice: "9000",
    location: "TOY SHOP 2, kharadi",
    isSale: true,
  },
];
